### ISSUE TITLE
Max size of Pointcloud very small.

### ISSUE THREAD

**Issue by Rauldg** [ESROCOS/types-sensor_samples#3]
The current maximum size for Pointclouds is too small.

Can it in principle be raised?

https://github.com/ESROCOS/types-sensor_samples/blob/79a1baa0584fcbea8af1f4e24290e85055efe16b/asn/Pointcloud.asn#L16

**Comment by mmunoz-gmv** [comment]
This package is superseded by the new package types-base, which provides configurable data sizes.
