### ISSUE TITLE
Broken reference to Time-Types

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/types-sensor_samples#4]
Compilation of this packages breaks at the moment with the error message of a missing ASN Module 'Time-Types' probably because of the changes in types/base

**Comment by mmunoz-gmv** [comment]
This package is no longer neede, as it is included in the new types-base. We need to update buildconf. In the meanwhile, you can remove all types/* packages except for types/base from the packages.autobuild file.

**Comment by Kynneb** [comment]
ah cool, good to know.
